### ISSUE TITLE
What is the project management layout of this project?

### ISSUE THREAD

**Issue by VermillionAzure** [ashish2199/Aidos#11]
I noticed that it appears you're not using Scrum or Agile, and there doesn't seem to be a "Code Review" or unit testing framework in place. How do you guys plan to control the quality of the project or the overall work "picture?"

**Comment by ashish2199** [comment]
@VermillionAzure  So far we arent following any methodology. So far we are following a adhoc process.
We dont have a formal code review yet. The code review so far is me seeing if the pull request are follow the general coding guidelines and those mentioned [here](https://github.com/ashish2199/Aidos/blob/master/CONTRIBUTING.md). With time I would like to involve more people into this. So far we are dependent on manual testing. 
Thanks for your question, I will try to look into things you have mentioned and see how they can be achieved.
