### ISSUE TITLE
KillableEntity?

### ISSUE THREAD

**Issue by CoreyHendrey** [ashish2199/Aidos#23]
I was wondering if we should make a KillableEntity, to separate out the death and health code from MoveableEntity, as it doesn't seem to fit too well to me.

**Comment by HarrisJT** [comment]
Well the health and the death still describe part of an entity. This is just one that moves.

**Comment by ashish2199** [comment]
Yeah we can have that. I don't see any problem with that.

**Comment by CoreyHendrey** [comment]
@HarrisJT yeah that was my thoughts :)
