### ISSUE TITLE
Discussion on which language to use

### ISSUE THREAD

**Issue by ashish2199** [ashish2199/Aidos#3]
## We have two options mainly we can use for making the game
- **JavaFX**
- **HTML5/Javascript**

Also provide your feedback on whether we should be using any game development framework or not. If yes , which one ?

**Please share what you are most familiar with.  Which one should we choose ? 
Any advantage of one over the other.**

**Comment by CiaranRoft** [comment]
I would rather do something in JavaFX.

**Comment by StewartWallace1115** [comment]
HTML5/ JavaScript. Try something new but I have used JavaFX in the past.

**Comment by llllllxu** [comment]
I prefer JavaFX

**Comment by ashish2199** [comment]
So far this is what i feel for me

JavaFX 
- Past experience with Java
- Following OOP and Structuring and organisation of code will be easier
- I feel we would be able to do advance animations and effects more easily

JS/HTML
- More tutorials and references
- Mobile Support and not dependent on JRE

So far I prefer JavaFX over JS.  Unless someone suggest more advantages with JS/HTML or has experience in making something similar we would go with JavaFX

@others Please provide your opinion.

**Comment by jlegendary** [comment]
I can do either or

**Comment by larfies** [comment]
I'm happy with either.

**Comment by jariss** [comment]
Never worked with either, but I know some Java and do want to learn JavaFx.

**Comment by CoreyHendrey** [comment]
+1 for JavaFX

**Comment by HarrisJT** [comment]
+1 for JavaFX, I find it really enjoyable and not to hard, we can even use css for styling. I would suggest people look at the docs if they haven't used it before.

**Comment by ashish2199** [comment]
## Since most of you want to work with JavaFX so we will be using it for making our game.

Thanks for your feedback.

# Issue Closed.
