### ISSUE TITLE
Regarding project ownership

### ISSUE THREAD

**Issue by ashish2199** [ashish2199/Aidos#35]
[**@CoreyHendrey**](https://github.com/CoreyHendrey) commented on [Nov 22, 2017, 5:23 AM GMT+5:30](https://github.com/ashish2199/Aidos/issues/28#issue-275899718 "2017-11-21T23:53:44Z - Replied by Github Reply Comments"):
> @ashish2199 
> Did you also want to submit pull requests for major changes, just so we can all discuss them? I'm unsure of the mentality for this project. IE, is it a total group effort. Or is it more a project that you own, and we are contributing too?
> 
> Thanks

I would like to clarify my stance
.
This project is about collaborating with people.
I am the owner the repository just because I first came up with this idea.Being a owner doesn't mean I would take decision what I feel is right, 
I would like to take into consideration what you guys want from the project and do things that way.

I recently asked a question on Github about how to get my code reviewed as a owner of the repository.
What has been suggested to me is to create a new branch for what I am working on and submit a pull request and getting it reviewed and merge it into the master branch. I will follow this patter from now on for any major changes I make.

I would like us to create a issue and discuss it if we are going to make a new design decision or deviating from our design as such changes have a large impact in future and shape how we will code in future.

**Comment by CoreyHendrey** [comment]
It sounds good to me :) I just wanted to know how we should be contributing. This is good. It looks like there are only a few of us active, anyway.
